services:
  namenode:
      image: apache/hadoop:3.3.6
      hostname: namenode
      command: [ "hdfs", "namenode" ]
      ports:
        - "9870:9870"
        - "8020:8020"
      env_file:
        - ./config
      environment:
        ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      volumes:
        - ./jars:/opt/hadoop/jars
      networks:
        - spark-network
  datanode1:
      image: apache/hadoop:3.3.6
      hostname: datanode1
      command: [ "hdfs", "datanode" ]
      env_file:
        - ./config
      networks:
        - spark-network
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"   # Spark Master Web UI
      - "7077:7077"   # Spark Master port
    networks:
      - spark-network
    volumes:
      - ./spark-master:/opt/bitnami/spark/work

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:
      - ./spark-worker-1:/opt/bitnami/spark/work

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:
      - ./spark-worker-2:/opt/bitnami/spark/work


  spark-worker-3:
    image: bitnami/spark:latest
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:
      - ./spark-worker-3:/opt/bitnami/spark/work


networks:
  spark-network:
    driver: bridge
